# Generated by Django 3.0.4 on 2023-11-17 02:40

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('[a-zA-Z0-9_]$')], verbose_name='ユーザーID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='メールアドレス')),
                ('birthday', models.DateField(blank=True, default='1900-12-30', null=True, verbose_name='誕生日')),
                ('icon', models.ImageField(upload_to=main.models.savePath, verbose_name='アイコン')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='登録日')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '女性'), (2, '男性'), (3, 'その他')], default=1, null=True, verbose_name='性別')),
                ('myouji', models.CharField(max_length=255, verbose_name='姓')),
                ('namae', models.CharField(max_length=255, verbose_name='名')),
                ('post', models.CharField(max_length=9, verbose_name='郵便番号')),
                ('pref', models.CharField(max_length=255, verbose_name='都道府県名')),
                ('prefDetail', models.CharField(max_length=400, verbose_name='住所詳細')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
            managers=[
                ('objects', main.models.MyUserManager()),
            ],
        ),
    ]
