# Generated by Django 3.0.4 on 2023-11-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='icon',
            field=models.ImageField(upload_to='media/main/', verbose_name='アイコン'),
        ),
    ]
