# Generated by Django 3.0.4 on 2023-11-17 05:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231117_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='icon',
            field=models.ImageField(upload_to=main.models.savePath, verbose_name='アイコン'),
        ),
    ]
