# Generated by Django 3.0.4 on 2023-11-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231117_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
