# Generated by Django 3.0.4 on 2023-11-18 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231117_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='username',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(5, 16), django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$')], verbose_name='ユーザーID'),
        ),
    ]
