# Generated by Django 3.0.4 on 2023-11-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231118_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='mail_deriv',
            field=models.BooleanField(default=False, verbose_name='メール配信希望'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='メールアドレス'),
        ),
    ]
