# Generated by Django 3.0.4 on 2023-11-25 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20231121_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTable',
            fields=[
                ('item_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='商品ID')),
                ('item_name', models.TextField(unique=True, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='値段/個')),
                ('sale_flg', models.BooleanField(default=True, verbose_name='販売ステータス')),
            ],
            options={
                'verbose_name': '商品テーブル',
                'verbose_name_plural': '商品テーブル',
            },
        ),
        migrations.CreateModel(
            name='CartTable',
            fields=[
                ('cart_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='カートID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='カート作成日時')),
                ('update', models.DateField(auto_now=True, verbose_name='カート更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '注文カート',
                'verbose_name_plural': '注文カート',
            },
        ),
        migrations.CreateModel(
            name='CartDetailTable',
            fields=[
                ('detail_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='カート詳細ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='数量')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cart', to='main.CartTable', verbose_name='カートID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='main.ItemTable', verbose_name='商品ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'カート詳細',
                'verbose_name_plural': 'カート詳細',
            },
        ),
    ]
