# Generated by Django 3.0.4 on 2023-11-27 00:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cartdetailtable_carttable_itemtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetailtable',
            name='user_id',
        ),
        migrations.AddField(
            model_name='carttable',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='注文状況'),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='item_img',
            field=models.ImageField(default='main/item/default_img.jpg', upload_to=main.models.saveItemPath),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='item_name',
            field=models.TextField(max_length=30, unique=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='icon',
            field=models.ImageField(default='main/icon/default_icon.png', upload_to=main.models.savePath, verbose_name='アイコン'),
        ),
    ]
