# Generated by Django 3.0.4 on 2023-11-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20231127_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
