# Generated by Django 3.0.4 on 2023-11-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20231127_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='item_name_eng',
            field=models.TextField(default='<django.db.models.fields.AutoField>', max_length=50, verbose_name='商品名(english)'),
        ),
        migrations.AlterField(
            model_name='carttable',
            name='slug',
            field=models.SlugField(blank=True, default='<django.db.models.fields.related.ForeignKey><django.db.models.fields.AutoField>', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='slug',
            field=models.SlugField(blank=True, default='<django.db.models.fields.AutoField>', max_length=20, null=True),
        ),
    ]
