# Generated by Django 3.0.4 on 2023-11-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20231127_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttable',
            name='slug',
        ),
    ]
