# Generated by Django 3.0.4 on 2023-11-28 02:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_carttable_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetailtable',
            options={'verbose_name': 'カート詳細テーブル', 'verbose_name_plural': 'カート詳細テーブル'},
        ),
        migrations.AlterField(
            model_name='cartdetailtable',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cart_item', to='main.ItemTable', verbose_name='商品ID'),
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='注文ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='注文確定日')),
                ('ordered', models.BooleanField(default=False, verbose_name='発送状況')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '注文テーブル',
                'verbose_name_plural': '注文テーブル',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailTable',
            fields=[
                ('detail_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='注文詳細ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='数量')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='main.CartTable', verbose_name='注文ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order_item', to='main.ItemTable', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '注文詳細テーブル',
                'verbose_name_plural': '注文詳細テーブル',
            },
        ),
    ]
