# Generated by Django 3.0.4 on 2023-11-28 03:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20231128_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='address',
            field=models.TextField(default='', max_length=255, verbose_name='住所詳細'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='arrive',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='到着予定日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertable',
            name='pay',
            field=models.IntegerField(choices=[(1, 'クレジットカード'), (2, '代金引換'), (3, '後払い決済'), (4, '振込')], default=1, verbose_name='支払方法'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='post',
            field=models.TextField(default='', max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='postage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='送料'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='pref',
            field=models.TextField(default='', max_length=20, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='to_firstname',
            field=models.TextField(default='', verbose_name='送り先(名前)'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='to_lastname',
            field=models.TextField(default='', verbose_name='送り先(苗字)'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='total_pay',
            field=models.IntegerField(default=1, verbose_name='合計金額'),
        ),
    ]
