# Generated by Django 3.0.4 on 2023-11-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20231128_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailtable',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.OrderTable', verbose_name='注文ID'),
            preserve_default=False,
        ),
    ]
