# Generated by Django 3.0.4 on 2023-11-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_orderdetailtable_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailtable',
            name='cart_id',
        ),
    ]
