# Generated by Django 3.0.4 on 2023-11-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_orderdetailtable_cart_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carttable',
            options={'verbose_name': 'カートテーブル', 'verbose_name_plural': 'カートテーブル'},
        ),
        migrations.AlterModelOptions(
            name='usertable',
            options={'verbose_name': 'ユーザーテーブル', 'verbose_name_plural': 'ユーザーテーブル'},
        ),
    ]
