# Generated by Django 3.0.4 on 2023-11-29 01:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20231129_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailtable',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='main.OrderTable', verbose_name='注文ID'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='post',
            field=models.TextField(default='', max_length=84, validators=[django.core.validators.RegexValidator('^[0-9]{3}-[0-9]{4}$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='post',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{3}-[0-9]{4}$')], verbose_name='郵便番号'),
        ),
    ]
