# Generated by Django 3.0.4 on 2023-11-29 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20231129_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='postage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='送料'),
        ),
    ]
