# Generated by Django 3.0.4 on 2023-11-29 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231129_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetailtable',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='数量'),
        ),
    ]
