# Generated by Django 3.0.4 on 2023-11-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20231129_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='town',
            field=models.CharField(default='', max_length=255, verbose_name='市町村'),
        ),
    ]
