# Generated by Django 3.0.4 on 2023-11-29 07:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_usertable_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='icon',
            field=models.ImageField(blank=True, default='main/icon/default_icon.png', null=True, upload_to=main.models.savePath, verbose_name='アイコン'),
        ),
    ]
