# Generated by Django 3.0.4 on 2023-12-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20231129_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='item_name_eng',
            field=models.TextField(default='', max_length=50, verbose_name='商品名(english)'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=20, null=True),
        ),
    ]
