# Generated by Django 3.0.4 on 2023-12-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20231205_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='town',
            field=models.CharField(default='', max_length=255, verbose_name='市町村'),
        ),
    ]
