# Generated by Django 3.0.4 on 2023-12-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_ordertable_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='points',
            field=models.IntegerField(default=0, verbose_name='保有ポイント'),
        ),
    ]
