# Generated by Django 3.0.4 on 2023-12-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_usertable_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='points',
            field=models.IntegerField(default=100, verbose_name='保有ポイント'),
        ),
    ]
