# Generated by Django 3.0.4 on 2023-12-13 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20231213_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailtable',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='main.OrderTable', verbose_name='注文ID'),
        ),
    ]
